// components/TermsOfService.tsx
import React from 'react';

export default function TermsOfService() {
  return (
    <div className="border border-green-500 bg-black text-green-400 font-mono">
      <div className="p-4 border-b border-green-500 flex items-center">
        <span className="text-gray-500 mr-2">$</span>
        <span className="text-lg">cat</span>
        <span className="text-white ml-2">terms_of_service.md</span>
      </div>
      
      <div className="p-4">
        <div className="mb-6">
          <h2 className="text-xl mb-2"># TERMS OF SERVICE</h2>
          <p className="text-gray-500 text-sm">// Last updated: {new Date().toLocaleDateString()}</p>
        </div>
        
        <div className="space-y-6 text-sm">
          <section>
            <h3 className="text-green-400 font-bold mb-2">## 1. ACCEPTANCE OF TERMS</h3>
            <p className="text-gray-400 mb-2">
              By accessing or using RushMyBookReport services, you agree to be bound by these Terms of Service. If you do not agree to all terms, you may not use our services.
            </p>
          </section>
          
          <section>
            <h3 className="text-green-400 font-bold mb-2">## 2. SERVICE DESCRIPTION</h3>
            <p className="text-gray-400 mb-2">
              RushMyBookReport provides AI-generated book report drafts for educational and reference purposes. Our service is intended to be used as a study aid and learning tool.
            </p>
          </section>
          
          <section>
            <h3 className="text-green-400 font-bold mb-2">## 3. USER RESPONSIBILITIES</h3>
            <p className="text-gray-400 mb-2">
              Users must:
            </p>
            <ul className="list-disc pl-5 text-gray-400 space-y-1">
              <li>Provide accurate information when using our services</li>
              <li>Use our services in accordance with their educational institution's academic integrity policies</li>
              <li>Not redistribute, sell, or claim our generated content as their own original work</li>
              <li>Use our services in compliance with all applicable laws</li>
            </ul>
          </section>
          
          <section>
            <h3 className="text-green-400 font-bold mb-2">## 4. ACADEMIC INTEGRITY</h3>
            <p className="text-gray-400 mb-2">
              Our services are designed to help users understand literature and improve their writing skills. Users are responsible for ensuring their use of our service complies with their institution's academic honesty policies. We strongly encourage users to:
            </p>
            <ul className="list-disc pl-5 text-gray-400 space-y-1">
              <li>Use our reports as reference materials only</li>
              <li>Properly cite our service if submitting derived work</li>
              <li>Develop their own understanding and insights based on our reports</li>
            </ul>
          </section>
          
          <section>
            <h3 className="text-green-400 font-bold mb-2">## 5. PAYMENT AND REFUNDS</h3>
            <p className="text-gray-400 mb-2">
              We offer two service tiers: Standard (24-hour delivery) and Rush (1-hour delivery). Payment is required before report generation. We offer a 100% satisfaction guarantee. If you're not satisfied with your report, contact us within 24 hours of delivery for a revision or refund.
            </p>
          </section>
          
          <section>
            <h3 className="text-green-400 font-bold mb-2">## 6. INTELLECTUAL PROPERTY</h3>
            <p className="text-gray-400 mb-2">
              Reports generated by our service are provided for the exclusive use of the purchasing user. You may not redistribute, publish, or sell reports generated by our service. We retain the right to use anonymized data to improve our AI systems.
            </p>
          </section>
          
          <section>
            <h3 className="text-green-400 font-bold mb-2">## 7. LIMITATION OF LIABILITY</h3>
            <p className="text-gray-400 mb-2">
              Our service is provided "as is" without warranties of any kind. We are not responsible for academic consequences resulting from the use of our service, including but not limited to plagiarism detection, academic penalties, or disciplinary actions.
            </p>
          </section>
          
          <section>
            <h3 className="text-green-400 font-bold mb-2">## 8. TERMINATION</h3>
            <p className="text-gray-400 mb-2">
              We reserve the right to terminate or suspend your access to our services at any time, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason.
            </p>
          </section>
          
          <section>
            <h3 className="text-green-400 font-bold mb-2">## 9. CHANGES TO TERMS</h3>
            <p className="text-gray-400 mb-2">
              We may modify these Terms at any time. Your continued use of our services after changes indicates your acceptance of the revised Terms.
            </p>
          </section>
          
          <section>
            <h3 className="text-green-400 font-bold mb-2">## 10. CONTACT INFORMATION</h3>
            <p className="text-gray-400 mb-2">
              For questions about these Terms, please contact us at:  
              support@rushmybookreport.com
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}